apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

namePrefix: prod-
nameSuffix: -v1

Labels:
- pairs:
    app: myapp
    env: prod
commonAnnotations:
  description: "prod env"

namespace: prod

images:
- name: myapp
  newName: easzlab.io.local:5000/myapp
  newTag: v1

configMapGenerator:
- name: myapp-cfg
  literals:
  - HAS_BUG=false

replicas:
- name: myapp
  count: 3

    #patches:
        #- patch: |-
        #   - op: replace
        #     path: /spec/replicas
        #     value: 3
        #  target:
        #    kind: Deployment
        #    name: myapp
