fullnameOverride: "test-app-v1"
replicaCount: 1
namespace: test
env: test
envs:
- name: HAS_BUG
  value: false
image:
  repository: easzlab.io.local:5000/myapp
  tag: v1
service:
  type: NodePort
  port: 8000
livenessProbe:
  httpGet:
    path: /health
    port: 8000
readinessProbe:
  httpGet:
    path: /health
    port: 8000
